[General]
monitorDir=C:\\Program Files\\Kiwix
reopenTab=true
moveToTrash=true
category=@Invalid()
language=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\n\0\0\0\x1a\0V\0i\0\x65\0t\0n\0\x61\0m\0\x65\0s\0\x65\0|\0v\0i)
contentType=@Invalid()

[view]
zoomFactor=1.3
